### PR TITLE
Material design colors (patch)

### PR DESCRIPTION
**Pull request by Shagon94**
Because I really like your keyboard but I miss the material design colors I had to do it myself.

### CODE REVIEW

**Comment by Shagon94** [comment]
screenshot_20170731-200034

**Comment by VladThodo** [comment]
Nicely done!
I wanted to focus a bit more in the design bit, but this really helps. Could you take a look on the other themes as well? Until then, I'm going to merge this.

**Comment by Shagon94** [comment]
sure, I am not a designer by the way, but maybe I can implement a color
picker for "make your own theme", also, would like to see the theme screen
settings first, and not the current one, anyway, ill try to make something
worth merging.

**Comment by VladThodo** [comment]
Thanks a lot! Any kind of help is appreciated. Seems that I have to add a credis section in the app.

**Comment by SealedJoy** [comment]
awesome project! I am very interested in creating some more themes, any advice on how to go about it? @Shagon94

**Comment by Shagon94** [comment]
This has been completed some time ago @SealedJoy , just look into the commit on how to do this, its rather simple, the hard part is to figure out a color scheme :)

**Pull request merged**
