### PR TITLE
Initial Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by Lennoard**
Hello, if you aren't using arrays values as keys, I would like to translate them too.

### CODE REVIEW

**Comment by VladThodo** [comment]
Thanks for getting involved! I pushed an update with couple more strings, could you translate them also before merging? And you can translate the button text also, I've hard-coded it, it's my fault

**Comment by flurbius** [comment]
I can do Spanish if you need it

**Comment by VladThodo** [comment]
@flurbius , of course man! Any translation is welcome!

**Comment by flurbius** [comment]
ok i will try to make some time to do that

On Jul 31, 2017 12:40 AM, "Vlad Todosin" <notifications@github.com> wrote:

@flurbius <https://github.com/flurbius> , of course man! Any translation is
welcome!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/VladThodo/behe-keyboard/pull/4#issuecomment-318913435>,
or mute the thread

**Comment by Lennoard** [comment]
Updated.

**Comment by VladThodo** [comment]
@Lennoard , I'm going to merge this. Thanks! I'll notify you when I add new strings.

**Pull request merged**
